build :
	$(MAKE) -C ./shared build
	$(MAKE) -C ./base build
	$(MAKE) -C ./front build
	$(MAKE) -C ./upstream-a build
	$(MAKE) -C ./upstream-b build
	$(MAKE) -C ./seneca-b build
	$(MAKE) -C ./seneca-c build

.PHONY : build

